Play travis
Otus-DevOps-2021-02/mdasaev_infra pull request #1
Opened 2021-04-05 19:31 UTC by mdasaev

need fixes

2021-04-06 08:07 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил небольшой комментарий. ДЗ возвращаю на доработку.

2021-04-06 08:07 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Посмотрите внимательно =)

2021-04-14 17:36 UTC, mdasaev commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
так, а куда смотреть?)

2021-04-15 11:51 UTC, mdasaev commented
Можно подробней в чем проблема здесь?

2021-04-16 08:50 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Все задания выполнены корректно, апрув!)

2021-04-16 08:50 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
В этой строке определенно что-то не так, там идет сравнение =)

2021-04-16 09:16 UTC, merged